/* Angular translation */
(function() {
  var app = angular.module("webSite", ["pascalprecht.translate"]);
  app.config([
    "$translateProvider",
    function($translateProvider) {
      $translateProvider.translations("pl", {
        "t-about": "o mnie",
        "t-services": "usługi",
        "t-projects": "projekty",
        "t-contact": "kontakt",
        "t-hero1": "programista webowy i web-designer",
        "t-hero2": "Jeśli zamierzasz o czymś myśleć, myśl odważnie",
        "t-about-text1": "Witam, nazywam się Konard Górski.",
        "t-about-text2":
          " Jestem pasjonatą IT, front-end developerem, UI/UX designerem i back-end developerem. Projektuję i tworzę strony internetowe jak również programuję w aplikacje w PHP",
        "t-skill": "zdolność uczenia się",
        "t-services-h": "Czym się zajmuję i co potrafię",
        "t-services-1": "Projektuję interfejsy, tworzę wireframey",
        "t-services-2h": "Projektowanie stron internetowych",
        "t-services-2": "Projektuję strony www, landing page i blogi.",
        "t-services-3h": "Programowanie stron internetowych",
        "t-services-3":
          "Tworzę strony internetowe używając technologii HTML5 / CSS3 / JavaScript / Jquery / AngularJS",
        "t-services-4":
          "Obecnie ponad połowa ruchu w internecie odbywa sie poprzez urządzenia mobilne. Tworzę strony, które dobrze działają na każdym urządzeniu. Wykorzystuję framework&apos;i Bootstrap, Foundation oraz Materialize CSS",
        "t-services-5":
          "Wdrażam systemy CMS, tworzę motywy i szablony w Drupal i Wordpress",
        "t-hire": "Gotowy do zatrudnienia",
        "t-hire-link": "kontakt do mnie",
        "t-projects": "Moje projekty",
        "t-umo": "Uniwersytet Mlodego Odkrywcy",
        "t-technologies": "Użyte technologie:",
        "t-ktkol": "Komisja Turystyki Kolarskiej",
        "t-hang": "Gra wisielec",
        "t-hang2": "Wisielec",
        "t-contact-h": "Kontakt",
        "t-name": "Imię",
        "t-surname": "Nazwisko",
        "t-email": "Adres e-mail",
        "t-message": "Wiadomość",
        "t-send": "Wyślij",
        BUTTON_TEXT_EN: "angielski",
        BUTTON_TEXT_PL: "polski"
      });

      $translateProvider.translations("en", {
        "t-about": "about me",
        "t-services": "services",
        "t-projects": "projects",
        "t-contact": "contact",
        "t-hero1": "web designer and front-end developer",
        "t-hero2": "If you are going to think, think BIG",
        "t-about-text1": "Hello, my name is Konard Górski.",
        "t-about-text2":
          " I am IT passionate, front-end developer, UI/UX designer and back-end developerem.I am projecting and developing web sites as well as developing server side apps in PHP",
        "t-skill": "learning",
        "t-services-h": "What I do and what I can",
        "t-services-1": "I project intarfaces, create wireframes",
        "t-services-2h": "Web design",
        "t-services-2": "I design web pages, landing pages and blogs.",
        "t-services-3h": "Front-end developement",
        "t-services-3":
          "I develop web sites using HTML 5 / CSS3 / JavaScript / Jquery / AngularJS",
        "t-services-4":
          "Over half of internet trafic is generated by mobile devices. I create webistes that are work and look great on all devices. I use Bootstrap, Foundation and Materialize CSS frame works.",
        "t-services-5":
          "I implement CMS systems, create themesand templates in Drupal and Wordpress",
        "t-hire": "Ready to hire",
        "t-hire-link": "contact me",
        "t-projects": "My projects",
        "t-umo": "Young Discoverer University",
        "t-technologies": "Technolgies applied:",
        "t-ktkol": "Bicycle Tourism Council",
        "t-hang": "The hangman game",
        "t-hang2": "Hangman",
        "t-contact-h": "Contact me",
        "t-name": "Name",
        "t-surname": "Last name",
        "t-email": "E-mail",
        "t-message": "Message",
        "t-send": "Send",
        BUTTON_TEXT_EN: "english",
        BUTTON_TEXT_PL: "polish"
      });

      $translateProvider.determinePreferredLanguage().fallbackLanguage(["pl"]);
      $translateProvider.useSanitizeValueStrategy("escape");
    }
  ]);

  app.controller("LanguageSwitchController", [
    "$translate",
    "$scope",
    function($translate, $scope) {
      $scope.changeLanguage = function(langKey) {
        $translate.use(langKey);
      };
    }
  ]);
})();
/* end angular translation */
function loadScript(url, callback) {
  // Adding the script tag to the head as suggested before
  var head = document.getElementsByTagName("head")[0];
  var script = document.createElement("script");
  script.type = "text/javascript";
  script.src = url;
  script.onreadystatechange = callback;
  script.onload = callback;
  // Fire the loading
  head.appendChild(script);
}
function loadCSS(filename) {
  var fileRef = document.createElement("link");
  fileRef.setAttribute("rel", "stylesheet");
  fileRef.setAttribute("type", "text/css");
  fileRef.setAttribute("href", filename);
  document.getElementsByTagName("head")[0].appendChild(fileRef);
}

var runAOS = function() {
  AOS.init({
    offset: 100,
    duration: 1500,
    easing: "ease-in-out-sine",
    delay: 100,
    once: true
  });
};

loadScript("https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js", runAOS);

// Google Analytics
(function(i, s, o, g, r, a, m) {
  i["GoogleAnalyticsObject"] = r;
  (i[r] =
    i[r] ||
    function() {
      (i[r].q = i[r].q || []).push(arguments);
    }),
    (i[r].l = 1 * new Date());
  (a = s.createElement(o)), (m = s.getElementsByTagName(o)[0]);
  a.async = 1;
  a.src = g;
  m.parentNode.insertBefore(a, m);
})(
  window,
  document,
  "script",
  "https://www.google-analytics.com/analytics.js",
  "ga"
);

ga("create", "UA-114917966-1", "auto");
ga("send", "pageview");
// end Google Analytics

/* image defer */
function initImgDefer() {
  var imgDefer = document.getElementsByTagName("img");
  for (var i = 0; i < imgDefer.length; i++) {
    if (imgDefer[i].getAttribute("data-src")) {
      imgDefer[i].setAttribute("src", imgDefer[i].getAttribute("data-src"));
    }
  }
}

window.onload = function() {
  document.body.classList.add("loaded");
  initImgDefer();
};

$(document).ready(function() {
  $(".parallax").parallax();
  $(".button-collapse").sideNav();

  /* Smooth Scroll */
  $("a.smooth-scroll").on("click", function(e) {
    e.preventDefault();
    var anchor = $(this);
    if (anchor.attr("href") == "#top") {
      $("html, body")
        .stop()
        .animate(
          {
            scrollTop: 0
          },
          1000
        );
    } else {
      $("html, body")
        .stop()
        .animate(
          {
            scrollTop: $(anchor.attr("href")).offset().top - 50
          },
          1000
        );
    }
  });

  /* navbar opacity */
  var headerH = $("header").height();
  var windowW = $(window).width();
  $(window).scroll(function() {
    scrollTop = $(window).scrollTop();

    if (scrollTop <= headerH) {
      $("nav.on-top").css({
        "background-color":
          "rgba(49, 27, 146," + (0 + scrollTop / headerH) + ")"
      });
    }

    if (scrollTop >= headerH - 60) {
      $("nav").removeClass("on-top");
    } else {
      $("nav").addClass("on-top");
    }
  });
});
